#!/bin/sh
GR="\033[1;32m"
NC="\033[0m"
echo -e "${GR}>>>>>>>> syncing..${NC}"
emerge --sync -qv
echo -e "${GR}>>>>>>>> checking updates..${NC}"
emerge -avDuNt --quiet-build>y --keep-going>y @world
echo -e "${GR}>>>>>>>> re-building apps due to updated dependencies..${NC}"
emerge -1t --quiet-build>y @preserved-rebuild
echo -e "${GR}>>>>>>>> cleaning unused apps..${NC}"
emerge --depclean
